name: Tests the examples in README
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v2
      - name: Use UV instead of pip
        run: rye config --set-bool behavior.use-uv=true
      - name: Install dependencies
        run: |
          pip install .[test]
      - name: Run pytest
        run: pytest tests
